"""sync models with db

Revision ID: a585bf1c973a
Revises: 0001
Create Date: 2026-06-02 16:54:52.323771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a585bf1c973a'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
