"""is active addition in user room 

Revision ID: dfa24381d301
Revises: a585bf1c973a
Create Date: 2026-06-03 09:23:46.300613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dfa24381d301'
down_revision: Union[str, None] = 'a585bf1c973a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_room_states', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_room_states', 'is_active')
    # ### end Alembic commands ###
