from sqlalchemy.orm import Session
from models.task_model import Task
from schemas.task_schema import TaskCreate, TaskUpdate

class TaskRepository:
    def __init__(self, db: Session):
        self.db = db

    def create_task(self, task_data: TaskCreate):
        # Convert Pydantic schema to SQLAlchemy Model
        new_task = Task(
            title=task_data.title,
            description=task_data.description,
            priority=task_data.priority
        )
        self.db.add(new_task)
        self.db.commit()
        self.db.refresh(new_task) # Gets the ID generated by the DB
        return new_task

    def get_task_by_id(self, task_id: int):
        return self.db.query(Task).filter(Task.id == task_id, Task.is_active == True).first()
    def delete_task_by_id(self, task_id: int):
        task =  self.db.query(Task).filter(Task.id == task_id, Task.is_active == True).first()
        if task:
            task.is_active = False 
            self.db.commit()
            self.db.refresh(task)
            return task
        return "No task found with the Respective ID"
    def edit_task_by_id(self, task_id : int, task_data: TaskUpdate):
        task =  self.db.query(Task).filter(Task.id == task_id, Task.is_active == True).first()
        if task:
            update_data = task_data.model_dump(exclude_none=True)
            for key, value in update_data.items():
                setattr(task, key, value)
            self.db.commit()
            self.db.refresh(task)
            return task
        return "No task found with the Respective ID"